"""Central configuration, loaded from environment variables / .env."""

from __future__ import annotations

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # --- Database ---
    database_url: str = "sqlite:///./vulngent.db"

    # --- LLM backend (OpenRouter, OpenAI-compatible) ---
    openrouter_api_key: str = ""
    openrouter_base_url: str = "https://openrouter.ai/api/v1"
    openrouter_model: str = "anthropic/claude-sonnet-4.5"

    # --- Auth (Sign in with Google / Microsoft) ---
    # If no provider client id is set, auth is bypassed entirely (local-dev friendly).
    google_client_id: str = ""
    # Microsoft (Azure AD / Entra ID) app registration client id.
    microsoft_client_id: str = ""
    # Microsoft tenant: "common" (any account), "organizations", "consumers", or a tenant id.
    microsoft_tenant: str = "common"
    # Optional Workspace lock-down: only accept accounts on this domain (e.g. "example.com").
    google_allowed_domain: str = ""
    # Secret used to sign the session cookie. Auto-generated per-process if unset;
    # set a stable value in prod so sessions survive restarts.
    session_secret: str = ""

    @property
    def google_enabled(self) -> bool:
        return bool(self.google_client_id)

    @property
    def microsoft_enabled(self) -> bool:
        return bool(self.microsoft_client_id)

    @property
    def auth_enabled(self) -> bool:
        return self.google_enabled or self.microsoft_enabled

    # --- GitHub ---
    github_token: str = ""

    # --- Slack ---
    slack_bot_token: str = ""
    slack_default_channel: str = ""

    # --- Email (SMTP) ---
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_username: str = ""
    smtp_password: str = ""
    smtp_from_address: str = ""
    smtp_use_tls: bool = True

    # --- Jira ---
    jira_server: str = ""
    jira_email: str = ""
    jira_api_token: str = ""
    jira_project_key: str = ""

    # --- Report whitelabeling (PDF/DOCX exports) ---
    report_company_name: str = "vulngent"
    report_title: str = "Vulnerability Remediation Report"
    report_logo_path: str = ""
    report_primary_color: str = "#111827"
    report_accent_color: str = "#2563EB"
    report_footer_text: str = "Confidential — generated by vulngent"


@lru_cache
def get_settings() -> Settings:
    return Settings()
